/// Flutter icons CoderMatthewsCustomClockIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CoderMatthewsCustomClockIcons
///      fonts:
///       - asset: fonts/CoderMatthewsCustomClockIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CoderMatthewsCustomClockIcons {
  CoderMatthewsCustomClockIcons._();

  static const _kFontFam = 'CoderMatthewsCustomClockIcons';

  static const IconData block_num_6 = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData block_num_7 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData block_num_8 = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData block_num_9 = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData dot = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData let_a = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData let_m = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData let_p = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData num_0 = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData num_1 = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData num_2 = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData num_3 = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData num_4 = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData num_5 = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData num_6 = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData num_7 = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData num_8 = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData num_9 = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData weather_cloudy = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData weather_foggy = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData weather_rainy = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData weather_snowy = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData weather_sunny = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData weather_thunderstorm = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData weather_windy = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData block_let_a = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData block_let_m = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData block_let_p = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData block_num_0 = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData block_num_2 = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData block_num_3 = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData block_num_4 = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData block_num_5 = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData block_num_1 = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData block_dot = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData block_degree = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData block_let_f = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData block_let_c = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData block_decimal = const IconData(0xe829, fontFamily: _kFontFam);
}
